repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.3
    hooks:
      - id: prettier
        entry: prettier --write
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
    hooks:
      - id: eslint
        entry: eslint --fix --ext js,jsx .
        files: \.(js|jsx|md)$
        additional_dependencies:
          - eslint-plugin-sort-imports-es6-autofix@latest
          - eslint@latest
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        entry: codespell --ignore-words=.codespell_ignore --skip="*.srt" --quiet-level=4 --check-filenames
        exclude: \.(csv|json|txt)$
